# Generated by Django 4.0.4 on 2022-04-28 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TWEET', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='aprecieri',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Topic', to='TWEET.topics'),
        ),
        migrations.AddField(
            model_name='posts',
            name='utilizator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_Post', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topics',
            name='utilizator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='User_Topic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topics',
            name='board',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Board', to='TWEET.board'),
        ),
    ]
